tw.local.sql[len].sql = "UPDATE (SELECT * FROM EKYC.TCJ_OCTO_MV_TASK_AUDIT WHERE 
			( STATUS = 'O' AND BPD_INST_ID IS NULL AND TASK_STAGE = ? AND TASK_ASSIGNED_BY IS NULL) OR (STATUS = 'W' AND BPD_INST_ID IS NOT NULL AND TASK_STAGE = ? AND TASK_ASSIGNED_BY IS NULL)
			ORDER BY TASK_RECEIVED_TIME FETCH FIRST ? ROWS ONLY WITH RS USE AND KEEP UPDATE LOCKS) 
			SET TASK_ASSIGNED_BY= ?, TASK_ASSIGNED_TO = ?, TASK_ASSIGNED_TIME =  CURRENT TIMESTAMP";
